backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "test"
    label: "Тест"
    folder: "content/ru/plays"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Название", name: "title", widget: "string"}
      - {label: "Контент", name: "body", widget: "markdown"}
